export const productData = [
  {
    id: 1,
    name: "Apple",
    price: 200,
    stock: true,
    category: "fruts",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pink_lady_and_cross_section.jpg",
    alt: "apple",
  },

  {
    id: 2,
    name: "Orange",
    category: "fruts",
    price: 200,
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Oranges_-_whole-halved-segment.jpg",
    alt: "orange",
    stock: false,
  },

  {
    id: 3,
    name: "Dragonfruit",
    price: 120,
    stock: true,
    category: "fruts",
    url: "https://upload.wikimedia.org/wikipedia/commons/4/43/Pitaya_cross_section_ed2.jpg",
    alt: "dragonfruit",
  },
  {
    id: 4,
    name: "Meet",
    price: 700,
    stock: true,
    category: "vegetable",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ae/FoodMeat.jpg",
    alt: "meet",
  },
  {
    id: 5,
    name: "Mango",
    price: 80,
    stock: false,
    category: "fruts",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/74/Mangos_-_single_and_halved.jpg",
    alt: "mango",
  },
  {
    id: 6,
    name: "Banana",
    price: 50,
    stock: true,
    category: "fruts",
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg",
    alt: "banana",
  },
  {
    id: 7,
    name: "Vegetable",
    price: 50,
    stock: true,
    category: "vegetable",
    url: "https://en.wikipedia.org/wiki/Vegetable#/media/File:Marketvegetables.jpg",
    alt: "Vegetable",
  },
  {
    id: 8,
    name: "Carrot",
    price: 150,
    stock: true,
    category: "vegetable",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg",
    alt: "banana",
  },
];
